from tutor import hooks


hooks.Filters.CONFIG_DEFAULTS.add_items([
    ("IAASSISTANT_OPENROUTER_API_KEY", ""),
    ("IAASSISTANT_OPENROUTER_MODEL", "openrouter/auto"),
    ("IAASSISTANT_OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
    ("IAASSISTANT_OPENROUTER_TIMEOUT", 30),
    ("IAASSISTANT_OPENROUTER_FALLBACK_MODELS", ""),
])


hooks.Filters.ENV_PATCHES.add_item((
    "openedx-common-settings",
    """
# IA Assistant XBlock - OpenRouter settings
OPENROUTER_API_KEY = "{{ IAASSISTANT_OPENROUTER_API_KEY }}"
OPENROUTER_MODEL = "{{ IAASSISTANT_OPENROUTER_MODEL }}"
OPENROUTER_BASE_URL = "{{ IAASSISTANT_OPENROUTER_BASE_URL }}"
OPENROUTER_TIMEOUT = {{ IAASSISTANT_OPENROUTER_TIMEOUT }}
OPENROUTER_FALLBACK_MODELS = "{{ IAASSISTANT_OPENROUTER_FALLBACK_MODELS }}"
"""
))
